from ui_icons import Icons

LOCALES = {
    "en": {
        "system_sync": f"{Icons.SYNC} CONNECTION",
        "synchro_subtitle": "Pick a channel and let's get the music started!",
        "standby_mode": f"{Icons.STANDBY} STANDBY",
        "standby_subtitle": "Pick a room where you want to listen to the radio.",
        "now_playing": "NOW PLAYING",
        "paused": "PAUSED",
        "idle": "IDLE",
        "stopped": "STOPPED",
        "presence_listening": "Listening to:",
        "presence_paused": "Paused",
        "artist": "Artist",
        "uploader": "Uploader",
        "title": "Title",
        "album": "Album",
        "genre": "Genre",
        "duration": "Length",
        "source": "Source",
        "platform": "Platform",
        "details_label": "Info",
        "shuffle_label": "Shuffle",
        "edit_queue_label": "Edit Queue",
        "clear_queue_label": "Clear Queue",
        "clear_queue_confirm": "Are you sure you want to clear the whole queue?",
        "remove_song_label": "Delete",
        "shuffle_feedback": "Queue shuffled!",
        "up_next": "Up Next",
        "empty": "Empty",
        "tuned_by": "Requested by:",
        "location": "Channel:",
        "placeholder_freq": "Pick a channel",
        "placeholder_genre": "Pick a genre",
        "placeholder_lang": "Language",
        "syncing": "Connecting...",
        "severing": "Disconnecting...",
        "resuming": "Resuming...",
        "cannot_pause_stopped": "You can't pause music while it's stopped.",
        "resuming_feedback": "Back to the music...",
        "pausing": "Pausing...",
        "stopping": "Stopping...",
        "forwarding": "Next track...",
        "nothing_playing": "Nothing's playing right now.",
        "cannot_seek_stopped": "You can't seek while the radio is stopped.",
        "cooldown_error": "Hold on a sec, the system is resting...",
        "jump_modal_title": "Jump to time",
        "timestamp_input_label": "Where should we jump? (mm:ss)",
        "format_error": "Use the mm:ss format!",
        "no_current_track": "Nothing to jump to.",
        "too_long": "The track isn't that long.",
        "jumping": "Jumping to:",
        "vol_modal_title": "Volume (0-100%)",
        "vol_input_label": "Set percentage",
        "invalid_number": "That's not a number!",
        "vol_range_error": "Enter a number between 0 and 100.",
        "vol_set": "Volume set to:",
        "no_playing_error": "Nothing's playing.",
        "play_label": "Play",
        "pause_label": "Pause",
        "stop_label": "Stop",
        "forward_label": "Next",
        "seek_label": "Seek",
        "back_label": "Back",
        "vol_label": "Volume",
        "details_btn_label": "Info",
        "queue_label": "Queue",
        "sever_uplink": "Disconnect",
        "info_visibility": "Info Window",
        "queue_visibility": "Queue Window",
        "admin_only": "You need to be an admin or system administrator for this.",
        "shown": "Shown",
        "hidden": "Hidden",
        "search_label": "Search",
        "weblink_label": "Link",
        "weblink_modal_title": "Add Link",
        "weblink_input_label": "YouTube / SoundCloud URL",
        "weblink_processing": "Processing link, please wait...",
        "weblink_error": "Invalid or unsupported link!",
        "weblink_added": "Link added to queue!",
        "last_label": "Last",
        "no_permission": "You don't have permission for this channel (or your role is too low).",
        "ui_mode_label": "UI Style",
        "ui_mode_full": "Full (Icons + Labels)",
        "ui_mode_compact": "Compact (Icons only)",
        "full_mode_label": "Full Mode",
        "full_mode_desc": "Rich UI with thumbnails and labels",
        "compact_mode_label": "Compact Mode",
        "compact_mode_desc": "Minimalist UI without labels",
        "style_placeholder": "Select UI Style",
        "search_modal_title": "YouTube Search",
        "search_input_label": "What are you looking for?",
        "search_results_title": "Search Results",
        "results_label": "Results",
        "search_processing": "Searching YouTube...",
        "error_generic": "An error occurred while processing your request.",
        "no_next_track": "No more tracks in the queue.",
        "no_prev_track": "No previous tracks in history.",
        "page": "Page",
        "total": "total",
        "unknown": "Unknown"
    },
    "hu": {
        "system_sync": f"{Icons.SYNC} CSATLAKOZÁS",
        "synchro_subtitle": "Válassz egy csatornát, és már indul is a zene!",
        "standby_mode": f"{Icons.STANDBY} KÉSZENLÉT",
        "standby_subtitle": "Válassz egy szobát, ahol hallgatni szeretnéd a rádiót.",
        "now_playing": "MOST SZÓL",
        "paused": "SZÜNETEL",
        "idle": "ÜRESJÁRAT",
        "stopped": "LEÁLLÍTVA",
        "presence_listening": "Hallgatja:",
        "presence_paused": "Megállítva",
        "artist": "Előadó",
        "uploader": "Feltöltő",
        "title": "Cím",
        "album": "Album",
        "genre": "Stílus",
        "duration": "Hossz",
        "source": "Forrás",
        "platform": "Platform",
        "details_label": "Infó",
        "shuffle_label": "Keverés",
        "edit_queue_label": "Lista szerkesztése",
        "clear_queue_label": "Lista ürítése",
        "clear_queue_confirm": "Biztosan törlöd a teljes várólistát?",
        "remove_song_label": "Törlés",
        "shuffle_feedback": "Lista megkeverve!",
        "up_next": "Következik",
        "empty": "Üres",
        "tuned_by": "Kérte:",
        "location": "Csatorna:",
        "placeholder_freq": "Válassz csatornát",
        "placeholder_genre": "Válassz stílust",
        "placeholder_lang": "Nyelvválasztás",
        "syncing": "Csatlakozás...",
        "severing": "Lecsatlakozás...",
        "resuming": "Folytatás...",
        "cannot_pause_stopped": "Álló helyzetben nem tudod szüneteltetni.",
        "resuming_feedback": "Zene folytatása...",
        "pausing": "Szünet...",
        "stopping": "Leállítás...",
        "forwarding": "Következő szám...",
        "nothing_playing": "Most épp semmi nem szól.",
        "cannot_seek_stopped": "Álló helyzetben nem tudsz tekerni.",
        "cooldown_error": "Várj egy kicsit, pihen a rendszer...",
        "jump_modal_title": "Ugrás időpontra",
        "timestamp_input_label": "Melyik perchez ugorjunk? (pp:mp)",
        "format_error": "Használd a pp:mp formátumot!",
        "no_current_track": "Nincs mihez ugrani.",
        "too_long": "Ilyen hosszú nincs is ez a szám.",
        "jumping": "Ugrás ide:",
        "vol_modal_title": "Hangerő (0-100%)",
        "vol_input_label": "Hány százalék legyen?",
        "invalid_number": "Ez nem egy szám!",
        "vol_range_error": "0 és 100 között adj meg valamit.",
        "vol_set": "Hangerő beállítva:",
        "no_playing_error": "Nem szól semmi.",
        "play_label": "Lejátszás",
        "pause_label": "Szünet",
        "stop_label": "Leállítás",
        "forward_label": "Következő",
        "seek_label": "Tekerés",
        "back_label": "Vissza",
        "vol_label": "Hangerő",
        "details_btn_label": "Infó",
        "queue_label": "Lista",
        "sever_uplink": "Lecsatlakozás",
        "info_visibility": "Infó ablak",
        "queue_visibility": "Várólista ablak",
        "admin_only": "Ehhez adminnak vagy rendszergazdának kell lenned.",
        "shown": "Látszik",
        "hidden": "Rejtve",
        "search_label": "Keresés",
        "weblink_label": "Link",
        "weblink_modal_title": "Link Hozzáadása",
        "weblink_input_label": "Illeszd be a YouTube / SoundCloud linket",
        "weblink_processing": "Link feldolgozása, kis türelmet...",
        "weblink_error": "Érvénytelen vagy nem támogatott link!",
        "weblink_added": "Link hozzáadva a várólistához!",
        "last_label": "Utolsó",
        "no_permission": "Nincs jogod ehhez a csatornához (vagy a rangod kevés).",
        "ui_mode_label": "Kezelőfelület stílusa",
        "ui_mode_full": "Teljes (Ikonok + Feliratok)",
        "ui_mode_compact": "Kompakt (Csak ikonok)",
        "full_mode_label": "Teljes mód",
        "full_mode_desc": "Részletes felület képekkel és feliratokkal",
        "compact_mode_label": "Kompakt mód",
        "compact_mode_desc": "Letisztult felület feliratok nélkül",
        "style_placeholder": "Válassz megjelenési stílust",
        "search_modal_title": "YouTube Keresés",
        "search_input_label": "Mit keresel?",
        "search_results_title": "Keresési Találatok",
        "results_label": "Találatok",
        "search_processing": "Keresés a YouTube-on...",
        "error_generic": "Hiba történt a kérés feldolgozása közben.",
        "no_next_track": "Nincs több szám a listában.",
        "no_prev_track": "Nincs korábbi szám az előzményekben.",
        "page": "Oldal",
        "total": "összesen",
        "unknown": "Ismeretlen"
    }
}

_radio_ref = None

def init_translate(radio_instance):
    global _radio_ref
    _radio_ref = radio_instance

def t(key):
    lang = "hu"
    if _radio_ref:
        lang = getattr(_radio_ref, "language", "hu")
    current_locales = LOCALES.get(lang, LOCALES["hu"])
    result = current_locales.get(key)
    if result is None:
        result = LOCALES["en"].get(key, key)
    return result
